### ISSUE TITLE
Not entirely sure what the groupName does

### ISSUE THREAD

**Issue by cmagorian** [puzzle/cert-manager-webhook-dnsimple#18]
I receive the following error when using either the default `groupName` or changing it to something unique as denoted in the docs:

```
Error presenting challenge: dnsimple.acme.tapcart.com is forbidden: User "system:serviceaccount:routing:cert-manager" cannot create resource "dnsimple" in API group "acme.tapcart.com" at the cluster scope
```

What is the groupName for and what should we be setting it to?

Do we need additional RBAC configurations for it?

**Comment by klopfenstein-puzzle** [comment]
Although this issue is somewhat old now, the `groupName` is mainly used by the [`APIService`](https://github.com/puzzle/cert-manager-webhook-dnsimple/blob/f6d110c78b1ffdcc968b75d3b789ebb3c86c7ccb/charts/cert-manager-webhook-dnsimple/templates/apiservice.yaml#L14) object and then referenced in other things generated by the chart such as `Deployments` and `Issuers`.  
Therefore, it defines the group name of the custom API server that gets registered in the cluster, i.e. `v1alpha1.<groupName>`.  

Perhaps the documentation is somewhat misleading in this regard:  
It states that it identifies the 'company that created the webhook', but ultimately it's just an API group name.  
Maybe the wording needs to be changed, or `groupName` be assigned a predefined value so the user wouldn't have to care about what needs to be configured there.

No additional RBAC should be required as appropriate ClusterRoles (and bindings) are generated.
That said, the `subject` of the `:domain-solver` ClusterRoleBinding is set according to the values of the `certManager` object in `values.yaml`.  
If permission errors occur, then perhaps those values have not been set correctly.
